const fields = {
  pt: {
    login: "Login",
    senha: "Senha",
    usuario: "Usuário",
    entrar: "Entrar",
    idioma: "Idioma",
    atencao: "Atenção",
    ok:"Ok",
    home: "Início",
    usuarios: "Usuários",
    benchmarks: "Benchmarks",
    sair: "Sair",
    editar_perfil: "Editar perfil",
    cancelar: "Cancelar",
    nome: "Nome",
    nova_senha: "Nova senha",
    confirmar_senha: "Confirmar senha",
    salvar: "Salvar",
    seu_usuario: "seu_usuario",
    sua_senha: "sua_senha",
    perfil: "Perfil",
    benchmark: "Benchmark",
    novo_usuario: "NOVO USUÁRIO",
    editar: "Editar",
    excluir: "Excluir",
    role: "Role",
    acoes: "Ações",
    novo_usuario_menor: "Novo usuário",
    editar_usuario: "Editar usuário",
    administrador: "Administrador",
    novo_benchmark: "Novo Benchmark",
    pais1: "País 1",
    pais2: "País 2",
    data_inicial: "Data Inicial",
    data_final: "Data Final",
    visualizar: "Visualizar",
    detalhes_benchmark: "Detalhes do Benchmark",
    criar_benchmark: "CRIAR BENCHMARK",
    fechar: "FECHAR",
    processando: "Processando...",
    casos_confirmados: "Casos Confirmados",
    obitos: "Óbitos",
    taxa_letalidade: "Taxa de Letalidade",
    indice_tendencia: "Índice de Tendência",
    legenda: "Legenda",
    azul: "Azul",
    vermelho: "Vermelho",
  },
  en: {
    login: "Login",
    senha: "Password",
    usuario: "Username",
    entrar: "Sign in",
    idioma: "Language",
    atencao: "Warning",
    ok: "Ok",
    home: "Home",
    usuarios: "Users",
    benchmarks: "Benchmarks",
    sair: "Logout",
    editar_perfil: "Edit profile",
    cancelar: "Cancel",
    nome: "Name",
    nova_senha: "New password",
    confirmar_senha: "Confirm password",
    salvar: "Save",
    seu_usuario: "your_username",
    sua_senha: "your_password",
    perfil: "Profile",
    benchmark: "Benchmark",
    novo_usuario: "NEW USER",
    editar: "Edit",
    excluir: "Delete",
    role: "Role", 
    acoes: "Actions",
    novo_usuario_menor: "New user",
    editar_usuario: "Edit user",
    administrador: "Administrator",
    novo_benchmark: "New Benchmark",
    pais1: "Country 1",
    pais2: "Country 2",
    data_inicial: "Start Date",
    data_final: "End Date",
    visualizar: "View",
    detalhes_benchmark: "Benchmark Details",
    criar_benchmark: "CREATE BENCHMARK",
    fechar: "CLOSE",
    processando: "Loading...",
    casos_confirmados: "Confirmed Cases",
    obitos: "Deaths",
    taxa_letalidade: "Fatality Rate",
    indice_tendencia: "Trend Index",
    legenda: "Legend",
    azul: "Blue",
    vermelho: "Red",
  },
  es: {
    login: "Iniciar sesión",
    senha: "Contraseña",
    usuario: "Usuario",
    entrar: "Ingresar",
    idioma: "Idioma",
    atencao: "Atención",
    ok: "Ok",
    home: "Inicio",
    usuarios: "Usuarios",
    benchmarks: "Benchmarks",
    sair: "Cerrar sesión",
    editar_perfil: "Editar perfil",
    cancelar: "Cancelar",
    nome: "Nombre",
    nova_senha: "Nueva contraseña",
    confirmar_senha: "Confirmar contraseña",
    salvar: "Guardar",
    seu_usuario: "tu_usuario",
    sua_senha: "tu_contraseña",
    perfil: "Perfil",
    benchmark: "Benchmark",
    novo_usuario: "NUEVO USUARIO",
    editar: "Editar",
    excluir: "Eliminar",
    role: "Role",
    acoes: "Acciones",
    novo_usuario_menor: "Nuevo usuario",
    editar_usuario: "Editar usuario",
    administrador: "Administrador",
    novo_benchmark: "Nuevo Benchmark",
    pais1: "País 1",
    pais2: "País 2",
    data_inicial: "Fecha Inicial",
    data_final: "Fecha Final",
    visualizar: "Visualizar",
    detalhes_benchmark: "Detalles del Benchmark",
    criar_benchmark: "CREAR BENCHMARK",
    fechar: "CERRAR",
    processando: "Procesando...",
    casos_confirmados: "Casos Confirmados",
    obitos: "Fallecimientos",
    taxa_letalidade: "Tasa de Letalidad",
    indice_tendencia: "Índice de Tendencia",
    legenda: "Leyenda",
    azul: "Azul",
    vermelho: "Rojo",
  },
};

export default fields;
