default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin123
  host: localhost
  port: 5432

development:
  <<: *default
  database: testedb

test:
  <<: *default
  database: testedb_test

production:
  <<: *default
  database: testedb_production
